# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DEhRJIil3FbX3mohns3xSj7WcoHiFIbw
"""

from abc import ABC, abstractmethod


class Payment(ABC):

    @abstractmethod
    def details(self):
        pass

    @abstractmethod
    def pay(self, amount):
        pass


class CardPayment(Payment):

    def __init__(self, card):
        self.card = card

    def details(self):
        return f"Card ****{self.card[-4:]}"

    def pay(self, amount):
        print(f"Card payment: ${amount:.2f}")
        return True


class UPIPayment(Payment):

    def __init__(self, upi):
        self.upi = upi

    def details(self):
        return f"UPI: {self.upi}"

    def pay(self, amount):
        print(f"UPI payment: ${amount:.2f}")
        return True


class PaymentCreator:

    def create(self, kind, data):
        if kind == "card":
            return CardPayment(data)
        elif kind == "upi":
            return UPIPayment(data)
        else:
            raise ValueError("Invalid payment method")


class PaymentGateway:

    def __init__(self, name, fee):
        self.name = name
        self.fee = fee

    def process(self, kind, data, amount):

        try:
            payment = PaymentCreator().create(kind, data)
        except ValueError as e:
            print(e)
            return False

        total = amount + (amount * self.fee / 100)

        print("Gateway:", self.name)
        print("Details:", payment.details())
        print(f"Total amount: ${total:.2f}")

        return payment.pay(total)


def main():

    gateway_name = input("Enter gateway (stripe/razorpay): ").lower()

    if gateway_name == "stripe":
        gateway = PaymentGateway("Stripe", 2.9)
    elif gateway_name == "razorpay":
        gateway = PaymentGateway("Razorpay", 2.0)
    else:
        print("Invalid gateway")
        return

    method = input("Enter method (card/upi): ").lower()

    if method == "card":
        data = input("Enter card number: ")
    elif method == "upi":
        data = input("Enter UPI ID: ")
    else:
        print("Invalid method")
        return

    try:
        amount = float(input("Enter amount: "))
    except ValueError:
        print("Invalid amount")
        return

    result = gateway.process(method, data, amount)

    if result:
        print("Transaction Successful")
    else:
        print("Transaction Failed")


if __name__ == "__main__":
    main()

